// version/version_generate.go
package version

//go:generate sh -c "VERSION=${VERSION:-$(git describe --tags --abbrev=0 2>/dev/null || echo 'v0.0.0')} && echo '// Code generated by go generate; DO NOT EDIT.\n\npackage version\n\nconst (\n\tVersion    = \"'\"${VERSION}\"'\"\n\tGitHash    = \"'\"$(git rev-parse --short HEAD 2>/dev/null || echo \"unknown\")\"'\"\n\tBuildTime  = \"'\"$(date -u +\"%Y-%m-%dT%H:%M:%SZ\")\"'\"\n\tGoVersion  = \"'\"$(go version | awk '{print $3}')\"'\"\n\tGitVersion = \"'\"$(git describe --tags --always 2>/dev/null || echo \"unknown\")\"'\"\n)' > version_generated.go"
